// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {

    /* header */
    var $header, $typeoutTitle;
    $typeoutTitle = $(".typeout-title");
    $header = $(".main-header");
    $.fn.typeOut = function(str, speed, callback) {
      var $target, count, intervalId;
      if (speed == null) {
        speed = 250;
      }
      if (!str) {
        str = $(this).text() || $(this).attr("data-typeout");
      }
      $target = $(this);
      count = 1;
      return intervalId = setInterval(function() {
        $target.html(str.substr(0, count));
        count += 1;
        if (count === str.length + 1) {
          clearInterval(intervalId);
          return callback($target);
        }
      }, speed);
    };
    $.fn.unwrapInner = function(selector) {
      var children;
      children = $(this).children();
      if (children.length === 1) {
        return $(this).html(children.html());
      }
    };
    return setTimeout(function() {
      return $typeoutTitle.typeOut(false, 150, function(el) {
        var $el;
        $el = $(el);
        $header.addClass("main-header--formatted");
        return $el.animate({
          opacity: 0
        }, 300, function() {
          $el.addClass("typeout-title--formatted").html("Next Generation Word Processing");
          return $el.animate({
            opacity: 1
          }, 300);
        });
      });
    }, 2000);
  });

}).call(this);
