// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var $header, $typeoutTitle;
    $typeoutTitle = $(".typeout-title");
    $header = $(".main-header");
    return setTimeout(function() {
      return $typeoutTitle.typeOut(false, 150, function(el) {
        var $el;
        $el = $(el);
        $header.addClass("main-header--formatted");
        return $el.animate({
          opacity: 0
        }, 300, function() {
          return $el.addClass("typeout-title--formatted").html("Next Generation Word Processing").animate({
            opacity: 1
          }, 300);
        });
      });
    }, 2000);
  });

}).call(this);
